# 核心提示映射
helpText=src/core/helpText.txt
winAsciiErr=src/core/winAsciiErr.txt

# Web UI 映射
pathMap=src/web-ui/pathMap.json
root_html=src/web-ui/index.html
root_css=src/web-ui/index.css
root_js=src/web-ui/index.js
