version=src/version.txt

# 核心提示映射
helpText=src/core/helpText.txt
winAsciiErr=src/core/winAsciiErr.txt

# Web UI 映射
pathMap=src/web-ui/pathMap.json
root=dist/web-ui/index.html
apidoc=dist/web-ui/apidoc/index.html
apidoc_zh=dist/web-ui/apidoc/zh.html
apidoc_en=dist/web-ui/apidoc/en.html